-- MySQL Script generated by MySQL Workbench
-- Thu Aug 12 16:37:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AspNetCoreDB
-- -----------------------------------------------------
-- Database thuc hanh ve asp net core.

-- -----------------------------------------------------
-- Schema AspNetCoreDB
--
-- Database thuc hanh ve asp net core.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AspNetCoreDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `AspNetCoreDB` ;

-- -----------------------------------------------------
-- Table `AspNetCoreDB`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AspNetCoreDB`.`Owner` ;

CREATE TABLE IF NOT EXISTS `AspNetCoreDB`.`Owner` (
  `OwnerId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(60) NULL,
  `DateOfBirth` DATE NULL,
  `Address` NVARCHAR(100) NULL,
  PRIMARY KEY (`OwnerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AspNetCoreDB`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AspNetCoreDB`.`Account` ;

CREATE TABLE IF NOT EXISTS `AspNetCoreDB`.`Account` (
  `AccountId` CHAR(36) NOT NULL,
  `DateCreated` DATE NULL,
  `AccountType` NVARCHAR(45) NULL,
  `OwnerId` CHAR(36) NOT NULL,
  PRIMARY KEY (`AccountId`),
  INDEX `fk_Account_Owner_idx` (`OwnerId` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Owner`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `AspNetCoreDB`.`Owner` (`OwnerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
